In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import spacy
import pickle

sns.set()

In [11]:
linear_model = pickle.load(open('models/linear_model.sav', 'rb'))
# result = loaded_model.score(X_test, Y_test)

In [37]:
import xgboost as xgb

xgb_model = pickle.load(open('models/xgb_model.sav', 'rb'))

In [7]:
nlp = spacy.load("en_core_web_lg")

In [13]:
def vectorizer(text):
    with nlp.disable_pipes():
        vector = np.array(nlp(text).vector)
    return vector

In [33]:
good_review = "I like this restaurant"
df = pd.DataFrame(vectorizer(good_review).reshape(1,-1))


linear_model.predict(df)

array([1], dtype=int64)

In [38]:
xgb_model.predict_proba(df)

# 70% certainty for the positive review

array([[0.29955024, 0.70044976]], dtype=float32)

In [39]:
bad_review = "I don't like this restaurant"
df = pd.DataFrame(vectorizer(bad_review).reshape(1,-1))

In [40]:
linear_model.predict(df)

array([0], dtype=int64)

In [41]:
xgb_model.predict_proba(df)

# 90% certainty for the negative review

array([[0.9168325 , 0.08316747]], dtype=float32)

In [43]:
bad_review2 = "Had to wait 2 hours to get my order"
df = pd.DataFrame(vectorizer(bad_review2).reshape(1,-1))

In [44]:
xgb_model.predict_proba(df)

array([[0.9428635 , 0.05713649]], dtype=float32)